# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForeignDataTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REMARK1', models.CharField(max_length=100, verbose_name='姓名')),
                ('REMARK2', models.CharField(max_length=100, verbose_name='身份证')),
                ('REMARK3', models.CharField(max_length=100, verbose_name='备注1')),
                ('REMARK4', models.CharField(max_length=100, verbose_name='备注2')),
                ('BODYXML', models.TextField(verbose_name='返回的报文体')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='EXCEL文件')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('TRAN_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='交易码')),
            ],
            options={
                'verbose_name': '外部数据测试案例',
                'verbose_name_plural': '外部数据测试案例',
            },
        ),
    ]
