# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 14:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignDataTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRAN_CODE', models.CharField(blank=True, max_length=100, verbose_name='交易码')),
                ('REMARK1', models.CharField(default='', max_length=100, verbose_name='姓名')),
                ('REMARK2', models.CharField(default='', max_length=100, verbose_name='身份证')),
                ('REMARK3', models.CharField(default='9', max_length=100, verbose_name='备注1')),
                ('REMARK4', models.CharField(default='9', max_length=100, verbose_name='备注2')),
                ('BODYXML', models.TextField(verbose_name='返回的报文体')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='EXCEL文件')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
            ],
            options={
                'verbose_name': '外部数据测试案例',
                'verbose_name_plural': '外部数据测试案例',
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='File')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '导入报文体文件',
                'verbose_name_plural': '导入报文体文件',
                'ordering': ['name'],
            },
        ),
    ]
