# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandtest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportFile',
        ),
        migrations.RemoveField(
            model_name='foreigndatatestcase',
            name='download',
        ),
        migrations.AddField(
            model_name='foreigndatatestcase',
            name='uploadfile',
            field=models.FileField(default='', upload_to='course/resource/%Y/%m', verbose_name='导入文件'),
        ),
    ]
