# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandtest', '0002_auto_20180115_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigndatatestcase',
            old_name='uploadfile',
            new_name='upload_file',
        ),
    ]
