# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandtest', '0003_auto_20180115_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigndatatestcase',
            name='upload_file',
            field=models.FileField(default='', upload_to='demandtest/resource/%Y/%m', verbose_name='导入文件'),
        ),
    ]
