# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 18:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandtest', '0004_auto_20180115_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(default='', upload_to='demandtest/resource/%Y/%m', verbose_name='导入文件')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
            ],
            options={
                'verbose_name': '文件导入信息',
                'verbose_name_plural': '文件导入信息',
            },
        ),
        migrations.AlterField(
            model_name='foreigndatatestcase',
            name='REMARK1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='foreigndatatestcase',
            name='REMARK2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='foreigndatatestcase',
            name='REMARK3',
            field=models.CharField(blank=True, default='9', max_length=100, verbose_name='备注1'),
        ),
        migrations.AlterField(
            model_name='foreigndatatestcase',
            name='REMARK4',
            field=models.CharField(blank=True, default='9', max_length=100, verbose_name='备注2'),
        ),
    ]
