# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandtest', '0006_auto_20180115_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigndatatestcase',
            old_name='uploadtime',
            new_name='uploadTime',
        ),
        migrations.RenameField(
            model_name='importfile',
            old_name='upload_file',
            new_name='uploadFile',
        ),
        migrations.RenameField(
            model_name='importfile',
            old_name='upload_time',
            new_name='uploadTime',
        ),
    ]
